language: node_js
node_js:
- 8.11.2
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
  - node_modules
  - client/node_modules
script:
- cd client
- yarn
- yarn test
