language: node_js
node_js:
- 8.11.2
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
  - node_modules
  - client/node_modules
script:
- cd client
- yarn
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: Kqj5uN26EnwdabZ7BtUs69b/+BSTopiCranaV5hMcZTxVOJy4t6Ypwr1a06nStKurRW/SpDrh49SjkR7FJgI7P0eN1h1LlRRgR89u144etjl7lea3e7aSL57cePbvlZHljZW1iLY0q9XdfgC3UAcU5I+M381wKVBAPzzICQndWhkyQW6+BokLytEwPcjtEMMpqaYgz2Z9OU+hD2C6iYRvX8yG9R1iqr4hM5GGkwc5Lk7qWwM+VmMX/EQu7lp226JVIj/W1bvpGyqQpclaeNndHQLzoqItJvZx0y6Vul1VbgaqNhzdHmj0E9AeugNhoZBfntkgQoqjIcv5deG7GnPftS3oJAVjCXquVfdME88kgEOggCgIMJV1jBT74y1CD8mR4lgJ9MafdDVXAZo9lxXgiTboJaWF1Ziich44yNU4BF0LJAzvAcPxSuu8amD6IfFJ1cf/7QqroazS/+uj0/YYcWRt3m+UuxMCj7gx6thJ3ui37H0M1HLmp4RtHfvXE1bpceofFS3CUq2Dnxmg4uKOA+qMLkbMdIbX0hUTvlvRwlFfWoCEV6bE/GQqSN5TEFMQWTjfShBCf4NBKMCEx8zEAyxPY7CoFU5o5HDCnbVKRO1Og9aXQzlfxWA1DUeT+5jZATMMHw+DHP3Phi8hAVXRUtwa6xD2p546hMabxprxSo=
  skip_cleanup: true
  app: awesome-counter
  on:
    repo: skyRoma/ReactGeneral
